package gu.com

import org.scalatest.{FlatSpec, Matchers}

class MainTest extends FlatSpec with Matchers {

  "blank board" should "look like this" in {
    val game = new Game()
    assert(""".......
             |.......
             |.......
             |.......
             |.......
             |.......""".stripMargin == game.toString())
  }

  "player move" should "update board" in {
    val game = new Game()
    game.move("x", 0)
    assert(""".......
             |.......
             |.......
             |.......
             |.......
             |x......""".stripMargin == game.toString())
  }

  "some player moves" should "update board" in {
    val game = new Game()
    game.move("x", 0)
    game.move("o", 0)
    game.move("x", 1)
    game.move("o", 0)
    assert(""".......
             |.......
             |.......
             |o......
             |o......
             |xx.....""".stripMargin == game.toString())
  }

    "player x wins" should "" in {
    val game = new Game()
    game.move("x", 0)
    game.move("o", 2)
    game.move("x", 0)
    game.move("o", 2)
    game.move("x", 0)
    game.move("o", 1)
    game.move("x", 0)
    assert(""".......
             |.......
             |x......
             |x......
             |x.o....
             |xoo....""".stripMargin == game.toString())
    assert(game.checkWin() == true)
  }
}
